### ISSUE TITLE
Doesn't work correctly with NerdTree windows

### ISSUE THREAD

**Issue by metalelf0** [merlinrebrovic/focus.vim#6]
If you have a split window with NerdTree, when coming back from Focus Mode, it gets replaced with an empty window with the same width. Not a big deal, the plugin is still usable, anyway :)

**Comment by ELLIOTTCABLE** [comment]
Would it be possible to automatically close NERDtree, specifically, when running this, and then re-open it when you disable it?

**Comment by merlinrebrovic** [comment]
That's one of the options, but I'm not using NERD tree, so I don't know how it would affect the flow.
